apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-web-app
  name: simple-web-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: simple-web-app
  sessionAffinity: None
  type: ClusterIP