apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-web-app
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
    - host:  {{ .Values.serviceAddress }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  name: http
