apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    app: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP